name = "HeyGirl Rewards"
client_id = "a8f37fdc6a172e01ab94e0b6ce1898e2"
application_url = "https://heygirl-rewards.onrender.com"
embedded = true

[access_scopes]
scopes = "read_customers,write_customers,read_orders,read_discounts,write_discounts,read_script_tags,write_script_tags,read_products,write_products"

[auth]
redirect_urls = ["https://heygirl-rewards.onrender.com/auth/callback"]

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = ["orders/updated"]
  uri = "/webhooks/orders-updated"

  [[webhooks.subscriptions]]
  topics = ["customers/create"]
  uri = "/webhooks/customers-create"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks/app-uninstalled"

  [[webhooks.subscriptions]]
  topics = ["orders/fulfilled"]
  uri = "/webhooks/orders-fulfilled"

  [[webhooks.subscriptions]]
  topics = ["refunds/create"]
  uri = "/webhooks/refunds-create"

  [[webhooks.subscriptions]]
  topics = ["customers/enable"]
  uri = "/webhooks/customers-enable"

  [[webhooks.subscriptions]]
  topics = ["customers/data_request"]
  uri = "/webhooks/customers-data-request"

  [[webhooks.subscriptions]]
  topics = ["customers/redact"]
  uri = "/webhooks/customers-redact"

  [[webhooks.subscriptions]]
  topics = ["shop/redact"]
  uri = "/webhooks/shop-redact"

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""

[app_proxy]
url = "https://heygirl-rewards.onrender.com/proxy"
subpath = "loyalty"
prefix = "apps"
